# Generated by Django 4.2.9 on 2024-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=10)),
                ('plublications', models.ManyToManyField(to='polls.plublication')),
            ],
        ),
    ]
